basePath: /
host: localhost:8081
info:
  contact: {}
  description: This is a service for storing files and getting their texts.
  title: Files Storing API
  version: "1.0"
paths:
  /get:
    get:
      description: Returns the content of a .txt file by ID
      parameters:
      - description: File ID
        in: query
        name: id
        required: true
        type: string
      produces:
      - text/plain
      responses:
        "200":
          description: OK
          schema:
            type: file
        "400":
          description: Invalid ID
          schema:
            type: string
        "404":
          description: File not found
          schema:
            type: string
      summary: Get file text
      tags:
      - storing
  /store:
    post:
      consumes:
      - multipart/form-data
      description: Upload and store a .txt file on the server
      parameters:
      - description: Text file to upload
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid input
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Store file
      tags:
      - storing
swagger: "2.0"
